export const env = {
  APP_ENV: process.env.APP_ENV,
  DATABASE_URL: process.env.DATABASE_URL,
  GOVBR_IDSP_AUTHORIZE_URL: process.env.GOVBR_IDSP_AUTHORIZE_URL,
  GOVBR_IDSP_CLIENT_ID: process.env.GOVBR_IDSP_CLIENT_ID,
  GOVBR_IDSP_CLIENT_SECRET: process.env.GOVBR_IDSP_CLIENT_SECRET,
  GOVBR_IDSP_REDIRECT_URI: process.env.GOVBR_IDSP_REDIRECT_URI,
  GOVBR_IDSP_SCOPE: process.env.GOVBR_IDSP_SCOPE,
  GOVBR_IDSP_TOKEN_URL: process.env.GOVBR_IDSP_TOKEN_URL,
  GOVBR_IDSP_USERINFO_URL: process.env.GOVBR_IDSP_USERINFO_URL,
  SERVICENOW_CSM_BASE_URL: process.env.SERVICENOW_CSM_BASE_URL,
  SERVICENOW_CSM_PASSWORD: process.env.SERVICENOW_CSM_PASSWORD,
  SERVICENOW_CSM_USERNAME: process.env.SERVICENOW_CSM_USERNAME,
  LOG_LEVEL: process.env.LOG_LEVEL,
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT
}
