export * from './auth-router'
export * from './dashboard-router'
export * from './flows-router'
export * from './health-router'
export * from './licenciamento-router'
export * from './notificacoes-router'
export * from './services-router'
export * from './tdv-router'
